name: Build and Deploy to GitHub Pages

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allow manual trigger
  push:
    branches: [ main ]  # Run on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3
        
      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}
        
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        
      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp
        
      - name: Create .nojekyll file
        run: touch private-repo-temp/.nojekyll
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: private-repo-temp/package-lock.json
        
      - name: Build project
        working-directory: private-repo-temp
        run: |
          cat > update-config.mjs << 'ENDSCRIPT'
          import fs from 'fs';
          import path from 'path';

          let configFile = '';
          if (fs.existsSync('vite.config.ts')) {
            configFile = 'vite.config.ts';
          } else if (fs.existsSync('vite.config.js')) {
            configFile = 'vite.config.js';
          } else {
            console.error('Could not find vite config file');
            process.exit(1);
          }
          
          console.log(`Found Vite config at: ${configFile}`);
          
          const newConfig = `
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';
import { componentTagger } from 'lovable-tagger';

export default defineConfig(({ mode }) => ({
  base: '/',
  server: {
    host: '::',
    port: 8080,
  },
  plugins: [
    react(),
    mode === 'development' && componentTagger(),
  ].filter(Boolean),
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    minify: true,
    sourcemap: false,
    cssMinify: true,
  },
}));`;
          
          fs.writeFileSync(configFile, newConfig);
          console.log('Vite config updated successfully!');
          ENDSCRIPT
          
          node update-config.mjs
          npm ci
          npm run build
        
      - name: Create 404.html
        working-directory: private-repo-temp/dist
        run: |
          cat > 404.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Page Not Found</title>
            <script>
              sessionStorage.setItem('redirect', window.location.pathname);
              window.location.href = '/';
            </script>
          </head>
          <body>
            <p>Redirecting...</p>
          </body>
          </html>
          EOF
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: private-repo-temp/dist
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          branch: gh-pages
          clean: true
