name: Build and Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:     # Manual trigger
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build-status.outcome }}

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v4

      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: private-repo-temp/package-lock.json

      - name: Install dependencies
        working-directory: private-repo-temp
        run: npm ci

      - name: Build
        id: build-status
        working-directory: private-repo-temp
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: private-repo-temp/dist

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: always()
    steps:
      - name: Report build status
        run: |
          if [[ "${{ needs.build.outputs.build-status }}" == "success" ]]; then
            echo "✅ Build succeeded!"
          else
            echo "❌ Build failed!"
          fi

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'success' }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 
