name: Build and Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:     # Manual trigger
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Checkout public repository
      - name: Checkout public repository
        uses: actions/checkout@v3

      # Set up SSH for private repo access
      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}

      # Add GitHub to known hosts
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # Clone private repository
      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp

      # Verify structure
      - name: Verify repository structure
        run: |
          echo "Public Repo:"
          ls -la
          echo "Private Repo:"
          ls -la private-repo-temp

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: private-repo-temp/package-lock.json

      # Inject base path in vite.config.ts
      - name: Patch Vite base path
        working-directory: private-repo-temp
        run: |
          echo "🔧 Injecting base path..."
          sed -i "/defineConfig({/a \ \ base: '/sparklingtracks.com/'," vite.config.ts
          echo "✅ vite.config.ts after patch:"
          cat vite.config.ts

      # Install & Build
      - name: Install & Build
        working-directory: private-repo-temp
        run: |
          echo "📦 Installing dependencies"
          npm ci
          echo "🔨 Building project"
          NODE_OPTIONS=--max_old_space_size=4096 npm run build
          echo "✅ Build output:"
          ls -la dist || echo "⚠️ dist folder not found!"

      # Optional: Disable Jekyll
      - name: Disable Jekyll
        run: |
          touch private-repo-temp/dist/.nojekyll

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: private-repo-temp/dist
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          branch: gh-pages
          clean: true
