name: Build and Deploy

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:     # Allow manual trigger
  push:
    branches:
      - main             # Run on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v3

      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}

      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: private-repo-temp/package-lock.json

      - name: Inject Vite Configuration with Path Aliases
        working-directory: private-repo-temp
        run: |
          cat <<EOT >> vite.config.ts
          import { defineConfig } from 'vite';
          import react from '@vitejs/plugin-react-swc';
          import path from 'path';
          import { componentTagger } from 'lovable-tagger';

          export default defineConfig(({ mode }) => ({
            server: {
              host: "::",
              port: 8080,
            },
            plugins: [
              react(),
              mode === 'development' && componentTagger(),
            ].filter(Boolean),
            resolve: {
              alias: {
                "@": path.resolve(__dirname, "./src"),
              },
            },
          }));
          EOT
          cat vite.config.ts

      - name: Install dependencies
        working-directory: private-repo-temp
        run: npm ci

      - name: Build project
        working-directory: private-repo-temp
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: private-repo-temp/dist
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          branch: gh-pages
          clean: true
