name: Build and Deploy to GitHub Pages

on:
  schedule:
    # Runs every hour (adjust as needed)
    - cron: '0 * * * *'
  # Allow manual trigger
  workflow_dispatch:
  # Run on pushes to the main branch of the public repo
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Add permissions needed for GitHub Pages
    permissions:
      contents: write
    steps:
      # Check out public repository
      - name: Checkout public repository
        uses: actions/checkout@v3
        
      # Set up SSH for deploy key
      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}
          
      # Add GitHub to known hosts
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      # Clone private repository to a temporary directory
      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp
          
      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: private-repo-temp/package-lock.json
          
      # Build project with verbose output
      - name: Build project
        working-directory: private-repo-temp
        run: |
          echo "Checking package.json build script:"
          grep -A 3 "scripts" package.json
          
          echo "Installing dependencies:"
          npm ci
          
          echo "Running build command:"
          npm run build
          
          echo "Checking build output:"
          ls -la
          if [ -d "dist" ]; then
            echo "dist directory found! Contents:"
            ls -la dist
          else
            echo "dist directory not found. Checking for other build directories:"
            find . -maxdepth 2 -type d -name "build" -o -name "dist" -o -name "out" -o -name "public"
          fi
          
      # Debug: Check Git version and ensure Git is installed
      - name: Debug Git
        run: |
          git --version
          which git
          echo "Git executable path: $(which git)"
          
      # Make sure Git is configured properly
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          
      # Add a test file to verify deployment is working
      - name: Add test file
        working-directory: private-repo-temp/dist
        run: |
          echo '<html><head><title>Test Page</title></head><body><h1>GitHub Pages Deployment Test</h1><p>If you can see this, the deployment is working!</p></body></html>' > test.html
          
      # Deploy built files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: private-repo-temp/dist  # Adjust if your build output is in a different directory
          token: ${{ secrets.DEPLOYMENT_TOKEN }}  # Use the personal access token
          branch: gh-pages  # Deploys to gh-pages branch
          clean: true       # Removes any files in the branch not in the build output
