name: Build and Deploy to GitHub Pages

on:
  schedule:
    # Runs every hour (adjust as needed)
    - cron: '0 * * * *'
  # Allow manual trigger
  workflow_dispatch:
  # Run on pushes to the main branch of the public repo
  push:
    branches: [ main ]

# Define environment variables for easy updates
env:
  PUBLIC_REPO_NAME: "cinnamonlife/sparklingtracks.com"
  SITE_PATH_PREFIX: "/sparklingtracks.com"
  SITE_TITLE: "Sparkling Tracks"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Check out public repository
      - name: Checkout public repository
        uses: actions/checkout@v3
        
      # Set up SSH for deploy key
      - name: Set up SSH deploy key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.PRIVATE_REPO_DEPLOY_KEY }}
          
      # Add GitHub to known hosts
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          
      # Clone private repository to a temporary directory
      - name: Clone private repository
        run: |
          git clone git@github.com:${{ secrets.PRIVATE_REPO_NAME }}.git private-repo-temp
          
      # Modify Vite configuration to use the correct base path
      - name: Update Vite configuration for GitHub Pages
        run: |
          echo "Modifying Vite configuration for GitHub Pages deployment..."
          
          # Find vite.config.js or vite.config.ts
          VITE_CONFIG=""
          if [ -f "private-repo-temp/vite.config.ts" ]; then
            VITE_CONFIG="private-repo-temp/vite.config.ts"
          elif [ -f "private-repo-temp/vite.config.js" ]; then
            VITE_CONFIG="private-repo-temp/vite.config.js"
          else
            echo "Could not find Vite configuration file. Searching for it..."
            VITE_CONFIG=$(find private-repo-temp -name "vite.config.*" | head -n 1)
            
            if [ -z "$VITE_CONFIG" ]; then
              echo "No Vite configuration file found. Creating one..."
              echo "import { defineConfig } from 'vite';" > private-repo-temp/vite.config.js
              echo "export default defineConfig({" >> private-repo-temp/vite.config.js
              echo "  // Original config" >> private-repo-temp/vite.config.js
              echo "});" >> private-repo-temp/vite.config.js
              VITE_CONFIG="private-repo-temp/vite.config.js"
            fi
          fi
          
          echo "Found Vite config at: $VITE_CONFIG"
          
          # Check if config is using defineConfig
          if grep -q "defineConfig" "$VITE_CONFIG"; then
            # Update the defineConfig to include the base path
            if grep -q "base:" "$VITE_CONFIG"; then
              # If base is already defined, update it
              sed -i "s|base: ['\"].*['\"]|base: '${{ env.SITE_PATH_PREFIX }}'|g" "$VITE_CONFIG"
            else
              # If base is not defined, add it before the first closing parenthesis or brace
              if grep -q "export default defineConfig({" "$VITE_CONFIG"; then
                # Format for object literal in defineConfig
                sed -i "s|export default defineConfig({|export default defineConfig({\n  base: '${{ env.SITE_PATH_PREFIX }}',|" "$VITE_CONFIG"
              else
                # Format for function in defineConfig
                sed -i "s|export default defineConfig(|export default defineConfig({\n  base: '${{ env.SITE_PATH_PREFIX }}',\n  ....|" "$VITE_CONFIG"
                sed -i "s|  ....|)|" "$VITE_CONFIG"
              fi
            fi
          else
            # Simpler format without defineConfig
            if grep -q "base:" "$VITE_CONFIG"; then
              sed -i "s|base: ['\"].*['\"]|base: '${{ env.SITE_PATH_PREFIX }}'|g" "$VITE_CONFIG"
            else
              sed -i "s|export default {|export default {\n  base: '${{ env.SITE_PATH_PREFIX }}',|" "$VITE_CONFIG"
            fi
          fi
          
          echo "Updated Vite configuration:"
          cat "$VITE_CONFIG"
          
      # Set up Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: private-repo-temp/package-lock.json
          
      # Build project
      - name: Build project
        working-directory: private-repo-temp
        run: |
          echo "Installing dependencies:"
          npm ci
          
          echo "Running build command with increased memory limit:"
          NODE_OPTIONS=--max_old_space_size=4096 npm run build
          
          echo "Build complete. Checking output:"
          ls -la dist || echo "dist directory not found!"
          
      # Add CNAME file for custom domain (uncomment when ready to use a custom domain)
      # - name: Add CNAME for custom domain
      #   working-directory: private-repo-temp/dist
      #   run: |
      #     echo "your-domain.com" > CNAME
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: private-repo-temp/dist
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          branch: gh-pages
          clean: true
